{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-cutadapt
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - cutadapt >=3
    - pigz
    - pandas {{ pandas }}
    - numpy
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_cutadapt
    - qiime2.plugins.cutadapt

  commands:
    - py.test --pyargs q2_cutadapt

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
